CREATE SCHEMA IF NOT EXISTS artechCms;

USE artechCms;

DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS credits;
DROP TABLE IF EXISTS articles_tags;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS managements;


CREATE TABLE managements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255),
  name varchar(255),
  password varchar(255),
  role varchar(255),
  url_avatar varchar(255)
);

CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category varchar(255)
);


CREATE TABLE articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint,
  manager_id bigint,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  current_state varchar(255),
  image_url varchar(255),
  slug varchar(255),
  subtitle varchar(255),
  text varchar(255),
  title varchar(255),
  FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
  FOREIGN KEY (manager_id) REFERENCES managements (id) ON DELETE CASCADE
);

CREATE TABLE tags (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tag varchar(255)
);

CREATE TABLE articles_tags (
  article_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  PRIMARY KEY (article_id, tag_id)
);

CREATE TABLE credits (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  article_id bigint,
  link varchar(255),
  name varchar(255),
  FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
);

CREATE TABLE users (
  id bigint GENERATED  BY DEFAULT  AS IDENTITY PRIMARY KEY,
  email varchar(255),
  name varchar(255),
  password varchar(255),
  urlAvatar varchar(255)
);


CREATE TABLE comments (
  article_id bigint,
  created_at TIMESTAMP,
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  text varchar(255),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
);

INSERT INTO managements (id, email,name,password,role,url_avatar)
  VALUES(900, 'johndoeadmin@email.com','John Doe Admin','123','Admin','');
INSERT INTO managements (id, email,name,password,role,url_avatar)
  VALUES(100, 'johndoe@email.com','John Doe','123','Author','');
INSERT INTO managements (id,email,name,password,role,url_avatar)
    VALUES(200, 'otherjohndoe@email.com','Other John Doe','123','Author','');

-- Service: ManagementService
--INSERT INTO managements (email,name,password,role,url_avatar)
--  VALUES('johndoemanager@email.com','John Doe Manager','123','Author','');

-- Service: ManagementService
--INSERT INTO managements (email,name,password,role,url_avatar)
--    VALUES('johndoeauth@email.com','John Doe Auth','123','Author','');

-- Service: ArticleService


-- Service: ArticleService - Update
INSERT INTO categories (id, category) VALUES (100, '');

INSERT INTO articles (id, category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
  VALUES (100, 100, 100 , CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-example-1', 'article example', 'article example','Article Example');
INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
  VALUES (100, 200 , CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-example-other-author-2', 'article example 2', 'article example 2','Article Example 2');

INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
  VALUES (100,100, CURRENT_DATE, CURRENT_DATE, 'disabled', '', 'article-disabled-1', 'article disabled ', 'article disabled','Article Disabled');
INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
  VALUES (100,200, CURRENT_DATE, CURRENT_DATE, 'disabled', '', 'article-disabled-2', 'article disabled ', 'article disabled','Article Disabled');

INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
  VALUES (100,100, CURRENT_DATE, CURRENT_DATE, 'draft', '', 'article-draft-1', 'article draft ', 'article draft','Article Draft');
INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
  VALUES (100,200, CURRENT_DATE, CURRENT_DATE, 'draft', '', 'article-draft-2', 'article draft ', 'article draft','Article Draft');

INSERT INTO users (id, email, name, password, urlAvatar)
  VALUES (100, 'usuario@email.com', 'Usuario', '123', '');

INSERT INTO comments (article_id, created_at, id, user_id, text)
  VALUES (100, CURRENT_DATE, 100, 100, 'Comentário Teste 1');
INSERT INTO comments (article_id, created_at, id, user_id, text)
  VALUES (100, CURRENT_DATE, 200, 100, 'Comentário Teste 2');
INSERT INTO comments (article_id, created_at, id, user_id, text)
  VALUES (100, CURRENT_DATE, 300, 100, 'Comentário Teste 3');
---- Service: ArticleService - Delete
--INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
--  VALUES (999,100, CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-delete-1', 'article delete ', 'article delete','Article Delete');
--INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
--  VALUES (999,200, CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-delete-other-author-2', 'article delete ', 'article delete','Article Delete');

-- Service: ArticleService - getAllByState
--INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
--  VALUES (100,100, CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-active-1', 'article active ', 'article active','Article Active');
--INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
--  VALUES (100,200, CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-active-2', 'article active ', 'article active','Article Active');


-- Service: ArticleService - getBySlug
--INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
--  VALUES (999,100, CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-by-slug-1', 'article by slug', 'article by slug','Article by slug');

-- Service: ArticleService - changeState
--INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
--  VALUES (999,100, CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-change-state-1', 'article change state', 'article change state','Article Change State');
--INSERT INTO articles (category_id, manager_id, created_at, updated_at, current_state, image_url, slug, subtitle, text, title)
--  VALUES (999,200, CURRENT_DATE, CURRENT_DATE, 'active', '', 'article-change-state-other-author-1', 'article change state other author', 'article change state other author','Article Change State other author');


-- Service: CommentService - deleteById







